version: '3.9'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./
        target: /app/src
      - type: volume
        source: app-node_modules
        target: /app/src/node_modules
      - type: volume
        source: app-next
        target: /app/src/.next
    init: true
    tty: true
volumes:
  app-node_modules:
  app-next:
